require "rubygems"
require 'rake'
require 'rake/testtask'
require 'cucumber/rake/task'
require 'selenium/rake/tasks'

task :cucumber do
	browsers = [{ :browserName => "firefox", :version => 9, :platform => "WINDOWS" }, { :browserName => "firefox", :version => 10, :platform => "WINDOWS" }]

	browsers.each do |browser|
    ENV['SELENIUM_BROWSERNAME'] = browser[:browserName]
    ENV['SELENIUM_BROWSERVERSION'] = browser[:version].to_s
    ENV['SELENIUM_BROWSERPLATFORM'] = browser[:platform]
		Rake::Task[:run_cucumber].execute(browser)
	end
end

Cucumber::Rake::Task.new(:run_cucumber) do |t|
  t.cucumber_opts = ["features"]
end