require 'jasmine'
require 'rspec/core/rake_task'
require 'testingbot'

namespace :jasmine do
  def run_jasmine_server
    ENV['JASMINE_PORT'] = '3001'
    Jasmine::Config.new.start_jasmine_server
  end

  desc "Execute Jasmine tests in a Chrome browser on testingbot"
  task :testingbot do
    run_jasmine_server
    Rake::Task['jasmine:testingbot:chrome'].execute
  end

  namespace :testingbot do
    desc "Execute Jasmine tests in Chrome and Firefox on TestingBot"
    task :all do
      run_jasmine_server
      threads = []
      [:chrome, :firefox].each do |browser|
        t = Thread.new do
          Rake::Task["jasmine:testingbot:#{browser}"].invoke
        end
        t.abort_on_exception = true
        threads << t
      end

      threads.each do |t|
        t.join
      end
    end
  end
end